dist: trusty
language: perl
perl: 
    - "5.20"

addons:
  apt:
    packages:
    - samtools
    - r-base

script: perl test.pl


after_failure:
    - echo "#######################FULL OUTPUT###########################"
    - find . -name "actual*" -exec cat {} \;
