dist: trusty
language: perl
perl: 
    - "5.24"

git:
  depth: 3 

addons:
  apt:
    packages:
    - samtools
    - r-base

before_install:
    - git clone https://github.com/oicr-gsi/gsi-website.git 
    - cd gsi-website && perl Makefile.PL && make && make install
    - cd -

script: 
    - perl Makefile.PL && make
    - PATH=bin:${PATH} make test
    - make install

after_failure:
    - echo "#######################FULL OUTPUT###########################"
    - find . -name "actual*" -exec cat {} \;
