dist: trusty
language: perl
perl: 
    - "5.20"

git:
  depth: 3 

addons:
  apt:
    packages:
    - samtools
    - r-base

before_install:
    - git clone https://github.com/oicr-gsi/bamqc.git
    - cd gsi-website && perl Makefile.PL && make && make install

script: perl test.pl

after_failure:
    - echo "#######################FULL OUTPUT###########################"
    - find . -name "actual*" -exec cat {} \;
